cargo-features = ["panic-immediate-abort", "profile-rustflags"]

[package]
name = "vulkanalia_project"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "immediate-abort"
strip = true
debug = 0
split-debuginfo = "off"
incremental = false
rustflags = ["-Zlocation-detail=none", "-Zfmt-debug=none"]

[target.'cfg(target_os = "linux")'.dependencies]
# To free static memory in RAM (Linux only)
madvise = "0.1.0"
# Compiler dependencies (Linux only)
openssl = { version = "0.10.78" }

# Give executable a desktop icon
[target.'cfg(target_os = "windows")'.dependencies]
winres = "0.1.12"

[dependencies]

# Errors
anyhow = "1.0.102"

# Byte conversion
bytemuck = { version = "1.25.0", features = ["derive"] }

# Vector math
glam = "0.33.0"

# 3d scene loading
gltf = "1.4.1"
ktx2-rw = "0.2.4"

# Logging
log = { version = "0.4.29", default-features = false, features = ["release_max_level_off"] }

# Meshoptimizer
meshopt = "0.6.2"

# Logging
pretty_env_logger = "0.5.0"

# Parallel processing
rayon = "1.12.0"

# Enum converter
strum = { version = "0.27.2", features = ["derive"]}

# Errors
thiserror = "2.0.18"

# Vulkan
vulkanalia = { version = "=0.35.0", features = ["libloading", "provisional", "window"] }
vulkanalia-vma = "0.9.0"

# For opening and manipulating windows
winit = "0.29"

[workspace]
members = ["builders"]
