// |                                            |
// | This file is auto-generated by the builder |
// |                                            |

#[repr(align(4096))]
struct AlignedAsset<T>(T);

const BLANK_ALBEDO: AlignedAsset<[u8; 682]> = AlignedAsset(*include_bytes!("../assets/textures/blank_albedo.ktx2"));
const CUTTLEFISH_ALBEDO: AlignedAsset<[u8; 225924]> = AlignedAsset(*include_bytes!("../assets/textures/cuttlefish_albedo.ktx2"));
