// |                                            |
// | This file is auto-generated by the builder |
// |                                            |

#![allow(dead_code)]

#[repr(align(4096))]
pub struct AlignedAsset(pub &'static[u8]);

// ------------KTX2 Textures------------

pub const START_ENUM_T: usize = 1;
pub const END_ENUM_T: usize = 2;
pub const COUNT_ENUM_T: usize = 2;

// 682 B
pub const BLANK_ALBEDO_T: AlignedAsset = AlignedAsset(include_bytes!("../assets/textures/blank_albedo.ktx2").as_slice());
// 220.63 KiB
pub const CUTTLEFISH_ALBEDO_T: AlignedAsset = AlignedAsset(include_bytes!("../assets/textures/cuttlefish_albedo.ktx2").as_slice());

// ------------Model Vertices-----------

pub const START_ENUM_V: usize = 3;
pub const END_ENUM_V: usize = 4;
pub const COUNT_ENUM_V: usize = 2;

// 109 B
pub const CUBE_V: AlignedAsset = AlignedAsset(include_bytes!("../assets/models_compressed/Cube.vertbuff").as_slice());
// 1.67 KiB
pub const LIMPET_V: AlignedAsset = AlignedAsset(include_bytes!("../assets/models_compressed/Limpet.vertbuff").as_slice());

// ------------Model Indices------------

pub const START_ENUM_I: usize = 5;
pub const END_ENUM_I: usize = 6;
pub const COUNT_ENUM_I: usize = 2;

// 38 B
pub const CUBE_I: AlignedAsset = AlignedAsset(include_bytes!("../assets/models_compressed/Cube.indbuff").as_slice());
// 89 B
pub const LIMPET_I: AlignedAsset = AlignedAsset(include_bytes!("../assets/models_compressed/Limpet.indbuff").as_slice());

#[derive(Clone, Copy, Debug, Default, Eq, strum::FromRepr, Hash, PartialEq)]
#[repr(usize)]
pub enum AssetId {
	#[default] None,
	BlankAlbedoTexture,
	CuttlefishAlbedoTexture,
	CubeVertices,
	LimpetVertices,
	CubeIndices,
	LimpetIndices,
}

pub fn get_asset_from_id(id: AssetId) -> AlignedAsset {
	match id {
		AssetId::None => {
			AlignedAsset(&[])
		},
		AssetId::BlankAlbedoTexture => {
			BLANK_ALBEDO_T
		},
		AssetId::CuttlefishAlbedoTexture => {
			CUTTLEFISH_ALBEDO_T
		},
		AssetId::CubeVertices => {
			CUBE_V
		},
		AssetId::LimpetVertices => {
			LIMPET_V
		},
		AssetId::CubeIndices => {
			CUBE_I
		},
		AssetId::LimpetIndices => {
			LIMPET_I
		},
	}
}
