// |                                            |
// | This file is auto-generated by the builder |
// |                                            |

#![allow(dead_code)]

#[repr(align(4096))]
pub struct AlignedAsset(pub &'static[u8]);

// ------------KTX2 Textures------------

pub const START_ENUM_T: usize = 1;
pub const END_ENUM_T: usize = 2;
pub const COUNT_ENUM_T: usize = 2;

// 670 B
pub const BLANK_ALBEDO_T: AlignedAsset = AlignedAsset(include_bytes!("../assets/textures/blank_albedo.ktx2").as_slice());
// 221.05 KiB
pub const CUTTLEFISH_ALBEDO_T: AlignedAsset = AlignedAsset(include_bytes!("../assets/textures/cuttlefish_albedo.ktx2").as_slice());

// ------------Model Buffers------------

pub const START_ENUM_M: usize = 3;
pub const END_ENUM_M: usize = 5;
pub const COUNT_ENUM_M: usize = 3;

// 1.99 KiB
pub const LIMPET_M: AlignedAsset = AlignedAsset(include_bytes!("../assets/mesh_files/Limpet.mesh").as_slice());
// 243 B
pub const CUBE_M: AlignedAsset = AlignedAsset(include_bytes!("../assets/mesh_files/Cube.mesh").as_slice());
// 19.35 KiB
pub const MONKEY_M: AlignedAsset = AlignedAsset(include_bytes!("../assets/mesh_files/Monkey.mesh").as_slice());

#[derive(Clone, Copy, Debug, Default, Eq, strum::FromRepr, Hash, PartialEq)]
#[repr(u16)]
pub enum AssetId {
	#[default] None,
	BlankAlbedoTexture,
	CuttlefishAlbedoTexture,
	LimpetMesh,
	CubeMesh,
	MonkeyMesh,
}

pub fn get_asset_from_id(id: AssetId) -> AlignedAsset {
	match id {
		AssetId::None => {
			AlignedAsset(&[])
		},
		AssetId::BlankAlbedoTexture => {
			BLANK_ALBEDO_T
		},
		AssetId::CuttlefishAlbedoTexture => {
			CUTTLEFISH_ALBEDO_T
		},
		AssetId::LimpetMesh => {
			LIMPET_M
		},
		AssetId::CubeMesh => {
			CUBE_M
		},
		AssetId::MonkeyMesh => {
			MONKEY_M
		},
	}
}
